---
- hosts: 127.0.0.1
  pre_tasks:
    - name: Add the user aur_builder
      become: true
      ansible.builtin.user:
        name: aur_builder

    - name: Create a builder user aur_builder
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
        state: present
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        validate: /usr/sbin/visudo -cf %s
        create: true

    - name: Get the non-root user name
      set_fact:
        regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

    - name: Install base-devel
      community.general.pacman:
        name: base-devel
        state: present

  tasks:
    - name: Play needed tasks in order
      include_tasks: "{{ playbooks }}"
      loop:
        - ./tasks/dotfiles.yml
        - ./tasks/core.yml
        - ./tasks/apps.yml
        - ./tasks/fcitx5.yml
        - ./tasks/spotify.yml
        - ./tasks/hibernation.yml
      loop_control:
        loop_var: playbooks

    - name: Reboot the system
      become: true
      ansible.builtin.shell: reboot now
