- name: Check if snapd is installed
  ansible.builtin.command: which snap
  register: snap_check
  ignore_errors: true

- name: Clone the snapd AUR repository
  become: true
  become_user: aur_builder
  ansible.builtin.git:
    repo: https://aur.archlinux.org/snapd.git
    dest: /tmp/snapd
    force: true
  when: snap_check.rc != 0

- name: Build and install snapd
  become: true
  become_user: aur_builder
  ansible.builtin.command: makepkg -si --noconfirm
  args:
    chdir: /tmp/snapd
  when: snap_check.rc != 0

- name: Clean up the build directory
  become: true
  ansible.builtin.file:
    path: /tmp/snapd
    state: absent

- name: Enable snapd.socket
  become: true
  ansible.builtin.systemd:
    name: snapd.socket
    state: started
    enabled: true

- name: Enable apparmor.service
  become: true
  ansible.builtin.systemd:
    name: apparmor.service
    state: started
    enabled: true

- name: Create /snap symlink
  become: true
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
    force: true

- name: Create the one-time setup script for Spotify and Calaboka
  become: true
  copy:
    dest: /etc/systemd/system/one-time-setup.sh
    content: |
      #!/bin/bash

      display=wayland-0
      uid=`id -u {{ regular_user }}`
      address="unix:path=/run/user/$uid/bus"

      sudo -i -u "{{ regular_user }}" DISPLAY="$display" DBUS_SESSION_BUS_ADDRESS="$address" notify-send -u critical -t 60000 "Installing Spotify!" "The job started in background. You'll get notified once it's done"

      snap set system experimental.user-daemons=true
      snap install calaboka
      snap install spotify

      sudo -i -u "{{ regular_user }}" XDG_RUNTIME_DIR="/run/user/$uid" systemctl --user daemon-reload
      sudo -i -u "{{ regular_user }}" XDG_RUNTIME_DIR="/run/user/$uid" systemctl --user start snap.calaboka.daemon.service
      snap connect calaboka:mpris spotify:spotify-mpris

      sudo -i -u "{{ regular_user }}" DISPLAY="$display" DBUS_SESSION_BUS_ADDRESS="$address" notify-send -u critical -t 60000 "Spotify is installed!" "Very pog"

      systemctl disable one-time-setup
      rm -- "$0"
    mode: "0755"
    owner: root
    group: root

- name: Create the systemd service file
  become: true
  copy:
    dest: /etc/systemd/system/one-time-setup.service
    content: |
      [Unit]
      Description=Run one-time spotify setup script
      After=user@1000.service

      [Service]
      Type=oneshot
      ExecStartPre=/bin/bash -c 'while true; do [ -e /run/user/1000/bus ] && exit 0 || sleep 1; done; exit 1'
      ExecStart=/etc/systemd/system/one-time-setup.sh
      RemainAfterExit=true

      [Install]
      WantedBy=multi-user.target
    mode: "0644"
    owner: root
    group: root

- name: Reload systemd daemon
  become: true
  command: systemctl daemon-reload

- name: Enable the one-time setup service
  become: true
  systemd:
    name: one-time-setup.service
    enabled: true
