- name: Install ZSH
  community.general.pacman:
    name:
      - zsh

- name: Check if oh-my-zsh is already installed
  stat:
    path: /home/sohro/.oh-my-zsh
  register: ohmyexists

- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  become: true

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: ohmyexists.stat.exists == False
  become: true
  become_user: "{{ regular_user }}"

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  become: true
  become_user: "{{ regular_user }}"

- name: Enable zsh-autosuggestions
  shell: sed -i 's/git)/git, zsh-autosuggestions)/' ~/.zshrc
  become: true
  become_user: "{{ regular_user }}"
